### ISSUE TITLE
Make manifest names an optional implementation detail

### ISSUE THREAD

**Issue by erikmunson** [spinnaker/keel#1019]
We've observed that in the majority case, the `name` of a manifest is a sort of unfamiliar implementation detail of configuring your app (which is what you likely _actually_ care about) and trying to understand its intended use, what inputs are valid, and how its uniqueness is determined is very tough to digest as someone getting on board and already learning lots of new concepts. Even our own team was going back and forth on the uniqueness of names, which is a clear indication the feature is hard to intuitively grasp.

Can we make the name optional and default it to something like `<appName>-manifest` (or if we do multi-app manifests later perhaps `<concatenatedAppNames>-manifest`), and then allow querying for a manifest via application name? This would effectively make the name an invisible implementation detail for the majority case where an app is the thing you're thinking about (I'm not even sure we've found a use case where the name is super important to understand or needs human attention yet)

**Comment by gal-yardeni** [comment]
Worth mentioning here that if doing it via newt, it defaults the name to  `<appName>-manifest` so I think it's valuable to have a consistent experience when creating the config ad-hoc.
