### ISSUE TITLE
Log messages not useful

### ISSUE THREAD

**Issue by emjburns** [spinnaker/keel#1085]
There are too many of these log messages: 
```
All keel exceptions should inherit from UserException or SystemException (got kotlinx.coroutines.TimeoutCancellationException). This is a bug.
```

This is in fact not a bug :D we should only be checking this for keel exceptions, not for all exceptions

**Comment by emjburns** [comment]
FYI @luispollo I assigned this to you to look into. I'm seeing hundreds of these messages and it's really distracting when trying to debug an issue.

**Comment by luispollo** [comment]
@emjburns I lowered the severity of these messages to `DEBUG` in #1095, which should allow you to filter these out when looking for errors. Do you think that’s enough, or should we get rid of the log message altogether?

**Comment by emjburns** [comment]
I think that should be good! Can you keep an eye on the frequency of them? Mostly I'd like them to only be present when it's an actual problem, and if that's the case then debug is great.

**Comment by luispollo** [comment]
I actually lowered it all the way to `TRACE` now, which I don't think we send to sumo, so the bad news is that I can't check the frequency, but the good news is that the noise should be gone from the logs.
