### ISSUE TITLE
Spike in BadSqlGrammarException and TimeoutCancellationException

### ISSUE THREAD

**Issue by luispollo** [spinnaker/keel#1089]
There's been a spike in the exceptions above in our logs over the last 12 hours:
![image](https://user-images.githubusercontent.com/1323478/80771335-0221f300-8b08-11ea-9e4d-dfc0688cd053.png)

They seem to always show up in pairs in the logs. Unfortunately, we don't seem to be logging the stack traces anywhere. They appear in the logs as:
```
All keel exceptions should inherit from UserException or SystemException (got org.springframework.jdbc.BadSqlGrammarException). This is a bug.
```
All the messages originate from UI calls:

_messagetime | level | message | x_spinnaker_user_origin
-- | -- | -- | --
05/01/2020 12:13:43.225 -0700 | ERROR | All keel exceptions should inherit from UserException or SystemException (got kotlinx.coroutines.TimeoutCancellationException). This is a bug. | deck
05/01/2020 12:13:43.225 -0700 | ERROR | All keel exceptions should inherit from UserException or SystemException (got org.springframework.jdbc.BadSqlGrammarException). This is a bug. | deck
05/01/2020 12:13:43.225 -0700 | ERROR | All keel exceptions should inherit from UserException or SystemException (got kotlinx.coroutines.TimeoutCancellationException). This is a bug. | deck
05/01/2020 12:13:43.225 -0700 | ERROR | All keel exceptions should inherit from UserException or SystemException (got kotlinx.coroutines.TimeoutCancellationException). This is a bug. | deck
05/01/2020 12:13:43.225 -0700 | ERROR | All keel exceptions should inherit from UserException or SystemException (got kotlinx.coroutines.TimeoutCancellationException). This is a bug. | deck

@emjburns suspected they may still be a result of the incident we had on 4/28 that put keel in a bad state, including some of the data in the database.

**Comment by luispollo** [comment]
@lorin FYI.

**Comment by luispollo** [comment]
The way I setup the `ResourceErrorCheck` event class to determine a simplified "origin" of the error in #1036 is such that the exception type will get evaluated every time such an event is instantiated, which is fine for new ones since I've added protections to never use any non-Spinnaker exception types, but for all the old events in the database, that's not the case, and so we log an error complaining it might be a bug, as in the example in the description, above.

The flow that leads to those event objects being instantiated is loading the event history from the UI, which potentially reads several days worth of events back in the past. There are no _new_ events with those characteristics in our database, but there are many from a few days back:

![image](https://user-images.githubusercontent.com/1323478/80835058-d86bd900-8ba6-11ea-8ebd-bca5cae4841c.png)

That's what's causing those messages to be logged. I will open a PR soon to lower the severity of those logs to `DEBUG` and make sure we log the stack traces for the originating exceptions going forward.

**Comment by emjburns** [comment]
Thanks so much for investigating. Just to make sure I get this right - this is happening because _in the past_ we failed for some reason and logged that reason + exception in the resource history. Now, when we load the resource history, we're getting this error message because it's reading that old message again?

**Comment by luispollo** [comment]
> Thanks so much for investigating. Just to make sure I get this right - this is happening because _in the past_ we failed for some reason and logged that reason + exception in the resource history. Now, when we load the resource history, we're getting this error message because it's reading that old message again?

Correct!
