### ISSUE TITLE
Can't deserialize ResourceCheckError objects

### ISSUE THREAD

**Issue by lorin** [spinnaker/keel#1107]
In prestaging, when we attempt to deserialize a ResourceCheckError event from the events table, keel throws a long exception. The relevant parts of the error message are::

```
MissingKotlinParameterException: Instantiation of [simple type, class com.netflix.spinnaker.keel.events.ResourceCheckError] value failed for JSON property exception due to missing (therefore NULL) value for creator parameter exception which is a non-nullable type ...

(through reference chain: com.netflix.spinnaker.keel.events.ResourceCheckError["exception"])
```

I think what's happening is that the `ResourceCheckError` class has an `exception` field which is required but is `@JsonIgnore'd`, so there's no `exception` field in the JSON payload. When Jackson tries to instantiate the object, it cannot construct a proper `exception` argument to pass the constructor at runtime.

I think this was introduced by #1095.

**Comment by luispollo** [comment]
I keep falling into these traps with jackson. Sigh... 😞

**Comment by lorin** [comment]
We should probably add ser/deser tests for every persistent event subclass so we can catch regressions like this in the future.

**Comment by luispollo** [comment]
> We should probably add ser/deser tests for every persistent event subclass so we can catch regressions like this in the future. 

Will do.
