### ISSUE TITLE
Returns 500 against /delivery-configs/diff when name field not in payload

### ISSUE THREAD

**Issue by lorin** [spinnaker/keel#1153]
If a request is missing information needed for authenticating, we currently return a 500 error due to an uncaught IllegalArgumentException.

For example: POST to `/delivery-configs/diff` and the body is missing a `name` field:

```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.netflix.spinnaker.keel.rest.AuthorizationSupport.hasApplicationPermission, parameter identifier
```

The payload should not require the name field to be present, so we need to update the auth check logic here so it doesn't rely on this field.

**Comment by gal-yardeni** [comment]
Marking it as a bug as it expects to get the delivery config name as an identifier, and it is not mandatory anymore. We will have to do the proper adjustments to the authz checks. cc: @luispollo

**Comment by lorin** [comment]
@gal-yardeni I changed the title and body to reflect your comment.

**Comment by gal-yardeni** [comment]
thank you @lorin ! I'm already fixing it.
