### ISSUE TITLE
Event rows have redundant,  possibly inconsistent data for timestamps

### ISSUE THREAD

**Issue by luispollo** [spinnaker/keel#1158]
The `event` table has a discrete `timestamp` column, but all event objects also have a `timestamp` field which gets encoded in the JSON blob stored in the `json` column. This can and has led to inconsistencies and should be fixed.

**Comment by luispollo** [comment]
Also see #1171.

**Comment by luispollo** [comment]
@robfletcher FYI.

**Comment by robfletcher** [comment]
This is denormalized model for sure, but the values should not be inconsistent.

We certainly could review the need for a timestamp column now that we have a ULID primary key on that table.

**Comment by robfletcher** [comment]
@luispollo I ran this query in main and it doesn't find any discrepancies (beyond milliseconds where we'd failed to use sub-second precision on the `timestamp` column)

```
select count(*) from event where TIMESTAMPDIFF(SECOND, timestamp, timestamp(json_unquote(json->"$.timestamp"))) > 0;
```

**Comment by luispollo** [comment]
@robfletcher The reason I thought we might have inconsistencies is that the instant used when serializing the event object to JSON via Jackson would be different than the instant obtained when writing to the `timestamp` column, but by a tiny amount. To your point on precision, maybe it doesn't matter with the precision we use. 🤷‍♂️

**Comment by robfletcher** [comment]
Well, we won't have that discrepancy in precision once we roll out #1225

**Comment by luispollo** [comment]
Right, so this still needs fixing then.

**Comment by robfletcher** [comment]
To get rid of the sub-second discrepancies?

**Comment by luispollo** [comment]
Right. If we think it matters enough.

**Comment by robfletcher** [comment]
I’ll do it today. Easy enough migration.
