### ISSUE TITLE
Consider adding MISSING_DEPENDENCY resource status

### ISSUE THREAD

**Issue by erikmunson** [spinnaker/keel#1162]
We've generally come to the conclusion that the concept of "vetoing" doesn't really belong in resource statuses. As we've all talked through it the sentiment has been that vetoing is a mechanical implementation detail we use to make things work, _not_ a top-level concept that users should be worrying about or forced to digest.

Recently [changes have been proposed](https://github.com/spinnaker/keel/pull/1157) to move the `VETOED` status over to `UNHAPPY`. Generally this works great, because today the main reason something would get vetoed is because it was flapping and we decided to throttle. The flapping case was the explicit meaning of `UNHAPPY`, so all seems well there.

To the point about vetoing being an implementation detail though, we now have a second case where vetoing comes into play as an under-the-hood mechanism: when there are missing dependencies that a resource needs before it can begin checking or actuating on desired state. Today the main case for this is load balancers and security groups referenced by a cluster resource, but we expect that resolving cross-resource dependencies will be a core part of how resources work even in a world with more resource kinds.

Based on that, I'd like to propose we add a `MISSING_DEPENDENCY` status to go along with `UNHAPPY`, so that we can disambiguate between the two real _reasons_ something isn't being checked. This would mean:
- Resources would have the `UNHAPPY` status if they are flapping, or were throttle because of flapping
- Resources would have the `MISSING_DEPENDENCY` status if they are waiting on something they need that isn't ready yet

While this would mean we'd end up with an additional status, it would really just be replacing today's VETOED status so we'd sort of be trading one for the other. It's also generally desirable to have lots of really clear and tightly scoped statuses, since we're going to have to model the complexity of all the different kinds of states a resource can be in _somewhere_, and doing it as hard-coded glue code in clients/UIs based on things like other metadata or error messages is far less maintainable.

**Comment by emjburns** [comment]
I agree with this approach, and I think it'll clear things up for users.

**Comment by luispollo** [comment]
@emjburns @erikmunson Closing this since #1157 was merged. Feel free to reopen if you disagree.
