### ISSUE TITLE
Add X-SPINNAKER-REQUEST-ID to new requests

### ISSUE THREAD

**Issue by lorin** [spinnaker/keel#1226]
Keel doesn't generate a `X-SPINNAKER-REQUEST-ID` for new requests that it generates. We should add support for this to make it easier to debug issues.

**Comment by luispollo** [comment]
Dupe of #1106.
See also #1122.

**Comment by luispollo** [comment]
See also https://github.com/spinnaker/keel/issues/1175

**Comment by lorin** [comment]
Closed as dupe.
