### ISSUE TITLE
activeServerGroup payload doesn't always have "image" field during deployments

### ISSUE THREAD

**Issue by lorin** [spinnaker/keel#1285]
When keel calls clouddriver to retrieve the active server group, sometimes the returned payload is missing the "image" field. [Keel assumes the image field is always present](https://github.com/spinnaker/keel/blob/7588f4519bf914e3bff46c2e296fd9f26488af09/keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/model/ActiveServerGroup.kt#L95).

The result is an error that looks like this:

```
com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException:
Instantiation of [simple type, class com.netflix.spinnaker.keel.clouddriver.model.ActiveServerGroup]
value failed for JSON property image due to missing (therefore NULL) value for creator 
parameter image which is a non-nullable type
```

This can happen during a deployment, shortly after a new ASG has been created. Clouddriver indexes information about ASGs separately than it indexes information about launch configs, and the launch config information is needed to populate the information in the returned `image` field.

Because the launch configuration indexes populate more slowly than the ASG indexes, we can hit this error condition during the following sequence of events:

1. keel starts a deployment for the *foo* cluster
2. clouddriver creates a new ASG inside the *foo* cluster: *foo-v123*
3. clouddriver updates its ASG cache with info about *foo-v123*
4. keel calls clouddriver to get the active server group of the "foo" cluster.
5. clouddriver returns info about *foo-v123*, but **it doesn't have build info yet**.
5. clouddriver updates its launch config cache which contains the build info associated with *foo-v123* (**TOO LATE!**)

**Comment by emjburns** [comment]
Nice sleuthing and description of the issue!

**Comment by lorin** [comment]
I'm going to close this out for now. This is a transient error that will eventually resolve itself. The best we could really do is improve the message in the exception log to make it clearer what is happening, but I don't think it's worth the effort in doing so.
