### ISSUE TITLE
jackson doesn't properly parse anchors and aliases in the managed delivery manifest

### ISSUE THREAD

**Issue by nimakaviani** [spinnaker/keel#1398]
I am creating this issue as a followup to our conversation during the SIG meeting. We noticed that managed delivery manifests that use anchors and aliases are not properly parsed even though the yaml document is totally valid.

Here is an example manifest.

```name: my-manifest
application: nimakspin
serviceAccount: sekret-service-account@spinnaker-test.net
artifacts: []
hasManagedResources: true
environments:
  - name: testing
    hasManagedResources: true
    resources:
    - &secgrp 
      kind: "ec2/security-group@v1"
      spec:
        moniker:
          app: "nimakspin"
        locations:
          account: "my-aws-account"
          vpc: "eksctl-demo-fargate-cluster/VPC"
          regions:
          - name: "us-west-2"
        description: "test LoadBalancer securityGroup by ALB Ingress Controller"
        inboundRules:
        - protocol: "TCP"
          portRange:
            startPort: 80
            endPort: 80
          blockRange: "0.0.0.0/0"
        - protocol: "TCP"
          portRange:
            startPort: 22
            endPort: 22
          blockRange: "0.0.0.0/0"
  - name: prod
    hasManagedResources: true
    resources:
    - *secgrp
```

The problem appears to be with Jackson failing to parse aliases and anchors where SnakeYAML parses the yaml document properly.

@luispollo suggested double passing of the yaml document, first into SnakeYAML and then into Jackson in order for the parsing of the manifest to work properly. That can be a relatively easy fix for this.

**Comment by luispollo** [comment]
Thanks for writing this up, @nimakaviani! Just adding a link to the original issue in Jackson for tracking: https://github.com/FasterXML/jackson-dataformats-text/issues/98
