### ISSUE TITLE
Resource deletion

### ISSUE THREAD

**Issue by robfletcher** [spinnaker/keel#165]
Do we want the ability for users to define a desired state of “this resource MUST NOT exist” and delete it if it ever does?

**Comment by luispollo** [comment]
@robfletcher Can you please add a description for this? What are "assets" in this context, "resources"?

**Comment by robfletcher** [comment]
Issue showing its age. Asset was the original name for what we now call resource. I’m increasingly convinced this is something we don’t need.

**Comment by emjburns** [comment]
Closing for now - this doesn't seem to be required for beta, and it's easy enough to create a new issue.
