### ISSUE TITLE
Removing security group name from a cluster desired state does not delete it

### ISSUE THREAD

**Issue by robfletcher** [spinnaker/keel#213]
Should red/black the cluster resulting in a new server group without the security group attached.

**Comment by robfletcher** [comment]
Issue is actually that you can't remove the application default security group so we should validate that in Keel and reject an update to a cluster that attempts to do so.

**Comment by robfletcher** [comment]
The app default security group is automatically created and associated with a server group if it doesn't exist. Couple of ways we could handle this:

1. Automatically add `${app-name}`, `nf-infrastructure`, and `nf-datacenter` to the resource when submitted.
2. Don't require those groups to be specified and ignore diffs where those are the only factor.

Thoughts @emjburns ?

**Comment by emjburns** [comment]
I like the idea that we automatically add it to the resource and return it. I want it to be specified and visible if possible. Seems like we could do this bit in a `ec2.netflix.clusters` plugin that extends the `ec2.clusters` plugin? Thinking about how to layer on netflix opinions is probably good to do up front.
