### ISSUE TITLE
Horizontal scaling of diff/actuation

### ISSUE THREAD

**Issue by robfletcher** [spinnaker/keel#226]
Currently we're using Spring events to trigger diff/actuation of a resource but that ties processing to a single instance. We should:

1. ensure only one instance is triggering diff/actuation of a given resource.
2. allow diff/actuation to be performed on a different instance to the one requesting it.

SQS? Keiko?

**Comment by robfletcher** [comment]
Based on the work in #224 we just need to create an alternate implementation of `ResourceCheckQueue`.

**Comment by emjburns** [comment]
+1 to this. Thoughts on Keiko vs SQS?

**Comment by robfletcher** [comment]
I'm kinda leaning towards SQS just because I don't want to have to re-activate Redis. Also our requirements are pretty damn simple so I don't know that we need anything more than the simplest of distributed queues.
