### ISSUE TITLE
Prevent duplicate resource checks when > 1 Keel instance

### ISSUE THREAD

**Issue by robfletcher** [spinnaker/keel#264]

**Comment by robfletcher** [comment]
Thinking of doing this via a distributed lock with SQL like Liquibase does. Make sense @cfieber?

**Comment by emjburns** [comment]
Kork has support for distributed locks which Swabbie uses, but this is for Redis. If you build distributed locking into SQL it would be great to provide it through an interface in kork!

**Comment by robfletcher** [comment]
Good idea. I’ll look at the Kork interface tomorrow.
