### ISSUE TITLE
More precise/actionable exceptions when spec validation fails

### ISSUE THREAD

**Issue by erikmunson** [spinnaker/keel#367]
When submitting a resource spec that is valid YAML, but _not a valid resource spec_, Keel sends back a pretty generic/unhelpful exception ([`Submitted resource with an incorrect structure, cannot convert to ${resource.kind} ${resource.spec}"`](https://github.com/spinnaker/keel/blob/8476be7592e36149a8f61dbb5ded3f2cb1a0d9af/keel-plugin/src/main/kotlin/com/netflix/spinnaker/keel/plugin/ResolvableResourceHandler.kt#L60)). For example, I ran into this message because the `image` resource kind requires an `application` field which I had omitted. This is compounded by the fact that on the gate side that exception gets tossed in the trash in favor of a generic retrofit exception object.

While I don't have an excellent technical solution to propose, I'm thinking roughly:

1. Exception messages that are capable of pointing to specific, actionable validation failures (e.g. `Missing field 'application'` or basic type info like `must be a string`)
2. The plumbing to get those validation failures in front of users at the gate level
3. Ideally, a way of doing item 1 that makes it easy to get basic validation for new/existing resources without a ton of extra work (e.g. how [K8s CRDs use OpenAPI](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema) to do validation in a standard/tooling-friendly way)

**Comment by luispollo** [comment]
@erikmunson Just to be clear, as far as the UX goes, the ask here is that when calling `POST /managed/delivery-configs`, the error information returned is structured such that it can be parsed by the client (UI, newt, etc.), similar to what was done for basic parsing errors in #821, correct?

**Comment by luispollo** [comment]
Related: #998

**Comment by luispollo** [comment]
Actually, validation errors are already returning nice, meaningful messages that get rendered correctly in the UI:
![image](https://user-images.githubusercontent.com/1323478/79018443-b099d000-7b28-11ea-8125-9f718f2f14eb.png)

I'll just make a tiny PR for deck that replaces "parsing" with "importing" in that label, and fixes the wrapping of the message to be by word and not character.

@erikmunson I'm leaning towards closing this at the moment. Please let me know if you have any objections.

@gal-yardeni FYI.

**Comment by erikmunson** [comment]
Yeah your work w/ `POST /managed/delivery-configs` + machine-parsable errors was precisely the experience this issue was trying to capture/ask for, I'd say it's been closable since that stage UI shipped!

**Comment by gal-yardeni** [comment]
@luispollo I think the issue I came across was with newt / the `managed/delivery-configs/diff`, which is also supposed to return a clear error message but currently doesn't.

**Comment by luispollo** [comment]
Oh, sorry @gal-yardeni. I saw @erikmunson's comment and pushed the Close button, just as your comment popped up. Feel free to reopen.
