### ISSUE TITLE
Expanded resource metadata in application summary endpoint

### ISSUE THREAD

**Issue by erikmunson** [spinnaker/keel#488]
We currently have [an endpoint](https://github.com/spinnaker/keel/blob/master/keel-api/src/main/kotlin/com/netflix/spinnaker/keel/rest/ApplicationController.kt) whose purpose is to serve up summary information about a specific application as it relates to Keel. The object that endpoint returns has a couple fields today: `hasManagedResources` which is a boolean, and `resources` which is an optionally included list of all the resource IDs that map to an app.

In the UI, we're now reaching a point where we need to get fresh (i.e. near-real-time) and slightly more detailed resource metadata for all the resources in an application, which we can then join together on the client with data from clouddriver. We've gotten pretty far relying on entity tags for indicating infrastructure is managed in the UI, but I don't believe they will serve us well as requirements grow and evolve (especially in the real-time cases). I propose we expand the existing application summary endpoint to include a new, **summarized** resource description that can be used by the UI without needing to download and deal with the entirety of resource definitions or make large numbers of fan-out API calls. Currently thinking something like:

```javascript
{
  hasManagedResources: true,
  resources: [
    // These would be some kind of ResourceSummary type
    {
      id: 'keel:resource:id',
      kind: 'cluster',
      status: 'HAPPY',
      moniker: {
        app: 'emburnstest',
        stack: 'prestaging',
        detail: 'foo'
      },
      locations: {
        // accountName can be handled in a generic way, but implicitly allows us
        // to find which cloud provider a resource is attached to
        accountName: 'prod',
        // Summarized regions, rather than full cloud provider-specific
        // metadata about regions/subnets/zones/etc.
        regions: ['us-west-2', 'us-east-1']
      }
    }
  ]
}
```
I'd want to stick to a few overall goals here:
- **Provide enough identifying metadata to do client side joins on clouddriver infrastructure**: This is basically kind + account + region + moniker info
- **Avoid cloud provider-specific identifiers if possible**: Across the rest of our APIs, we generally treat the concepts of `account` and `region` as being generic and applicable to any cloud provider. Many providers have their own interesting specifics (i.e. zones, subnets, etc.), but there is a lot of code in Deck (and I presume other services) that understands account + region at a core level and can then choose to delegate provider-specific concerns beneath that out to different modules. It'd be great to be able to do that here as well (as a relevant example, entity tags will apply themselves to infra with a matching account + region + moniker, regardless of provider)
- **Provide a UI-appropriate combination of desired state (i.e. `spec` fields) and current state (e.g. `status`):** it will be extremely useful on the UI side to combine the things we know about how a resource is configured and what it's current state/status actually is, because in practice both will show up in unison on most views

I suspect there are some interesting performance considerations here if we start polling for resource data (split by app) from the client regularly. We'll want to at least know what those are and be ready to tackle them if necessary.

**Comment by erikmunson** [comment]
@emjburns @robfletcher @asher

**Comment by erikmunson** [comment]
Implicit here is the idea that if we wanted the entire spec on the client for some reason, we could grab it via a resource-specific endpoint later based on the resource ID we get from this summary endpoint. We already do the same with things like server group/lb/security group details.

**Comment by emjburns** [comment]
This seems good to me. I think let's handle performance concerns when they start to hurt us. 
- For now, I'll try and build this information into `keel` by just querying for what I want.
- Querying for status might be a lot of work. If so, we can store status in a table and update it when we write the history events (status is calculated by looking at the history), or refresh it immediately after.
- If this is still performance-heavy, we'll deal with it later. I'm expecting the UI to call about every 30 seconds for each user/app that they have open, so we might need to do some caching.

An alternative strategy (one that I propose we don't go down) would be to figure out how to get this data in clouddriver for the resource. While that might make the UI loading easier, I think it is not very straight forward on the back end.
