### ISSUE TITLE
Normalizers should participate in desired state resolution

### ISSUE THREAD

**Issue by robfletcher** [spinnaker/keel#492]
Instead of being applied once on create/update of a resource, normalizers should be used when resolving desired state. This would mean the "normalized" resource is never persisted and normalizers can make different decisions as time passes. This would modularize the desired state resolution process and make testing handlers simpler.

**Comment by emjburns** [comment]
For this case we also need to think about how a user reasons about this. They might have questions like:
- What does my spec look like?
- What defaults were applied?
- How can I tell what changes you made?
- What is the fully resolved resource definition?

**Comment by robfletcher** [comment]
Yeah, I was thinking about that last night and got as far as realizing we're not making it any _worse_ as the existing implementation doesn't tell anyone about those decisions either!
