### ISSUE TITLE
ClusterHandler fails to create a valid diff when adding a new region

### ISSUE THREAD

**Issue by asher** [spinnaker/keel#499]
Steps to reproduce:

1) Have an existing valid cluster spec deployed only to region A
2) Ensure image is baked in regions A, B
3) Ensure there are no pre-existing serverGroups for the cluster in region B
4) Add region B to cluster spec and publish

This appears to result in `unable to resolve desired state` for the cluster.

**Comment by emjburns** [comment]
I can't reproduce this running locally with either just the cluster.yml or a cluster as part of a delivery config

**Comment by asher** [comment]
This was likely a different issue, which was masked by insufficient logging at the time.
