### ISSUE TITLE
API for validating resource spec

### ISSUE THREAD

**Issue by emjburns** [spinnaker/keel#509]
Returns validation errors, or that a resource is valid

**Comment by asher** [comment]
Ideally, this would validate all the way down to clouddriver. Validation that keel will accept a spec without actually submitting is a good first start, but I think there are many ways a spec can be invalid that are currently invisible to keel.

**Comment by robfletcher** [comment]
It's possible it makes sense to merge this endpoint with the on that returns a diff between the desired state this would resolve to and reality.
