### ISSUE TITLE
kind name shouldn't have to be unique across all api versions

### ISSUE THREAD

**Issue by emjburns** [spinnaker/keel#527]
This function: https://github.com/spinnaker/keel/blob/c09ce2cf6ee0d6f3d42137308b65ca0b4fa250c6/keel-api/src/main/kotlin/com/netflix/spinnaker/keel/Main.kt#L86-L94
makes it so that we're registering types by kind -> spec class. We should make this something like apiversion/kind -> spec class so that we can have a "cluster" for each cloud provider.

You shouldn't have to study every other object type in order to pick a unique name.

**Comment by robfletcher** [comment]
Yeah, sorry. I was lazy.
