### ISSUE TITLE
Handle missing appversion tag on server group

### ISSUE THREAD

**Issue by robfletcher** [spinnaker/keel#555]
If the AMI deployed to a server group is missing the `appversion` tag `ClusterHandler` will fail to resolve the current state. Instead we should resolved to a model with `appversion: null`, in which case the resource check will re-deploy.

**Comment by luispollo** [comment]
@robfletcher Question: we currently emit a `ArtifactVersionDeployed` while retrieving server groups in `ClusterHandler` if the app version across regions matches. In the case where the `appversion` tag is missing in only one of the regions, but matches in the other ones, what do we want to do?

**Comment by luispollo** [comment]
@robfletcher I noticed you moved this to "Needs review" _after_ you approved the PR that fixes it (#615)... Was that intentional? 😃
