### ISSUE TITLE
Apply PAUSED status to resources which a veto currently applies to

### ISSUE THREAD

**Issue by erikmunson** [spinnaker/keel#561]
We have a list of lovely resource statuses, which we're about to start surfacing in the UI. Another status we should start calculating is PAUSED — which should be chosen for a resource whenever it falls under the scope of an active veto plugin. Right now that means `ApplicationVeto`, but ideally we'd just check whether _any_ veto applies and return PAUSED if so.

**Comment by erikmunson** [comment]
For whoever implements this, here's how we currently check for whether a veto applies to a given resource as a way to get started: https://github.com/spinnaker/keel/pull/348/files#diff-909791cad394c56c8595f2e446444cf1R22-R43

tl;dr give VetoEnforcer a resource name and check `allowed`.

**Comment by luispollo** [comment]
@erikmunson I'll look at this.

**Comment by erikmunson** [comment]
Closed via #572
