### ISSUE TITLE
Export Titus Resource

### ISSUE THREAD

**Issue by emjburns** [spinnaker/keel#570]
Implement the "export a current resource" functionality for Titus

**Comment by luispollo** [comment]
@gal-yardeni I have an interest in picking this up as well, as I just spent some time working on improvements for the EC2 cluster export but this would give me an opportunity to implement a small feature end-to-end. Please let me know if you got something else you're working on, and I'd be happy to take it.

**Comment by gal-yardeni** [comment]
@luispollo Honestly I kind of want to dig into it, but let's talk offline!
