### ISSUE TITLE
Artifact Support for Docker images

### ISSUE THREAD

**Issue by emjburns** [spinnaker/keel#571]
For EC2 We currently support providing an "artifact" (name, type = DEB) with a cluster. When we check the state, we look up the latest version of that artifact based on the fact that debians have predictable versions and that we can know the order of those versions.

For example, the package `my-app` has the following versions:
```
my-app-0.45.0-h275.7324bd8
my-app-0.46.0-h276.3becf92
my-app-0.47.0-h277.b9873f6
my-app-0.48.0-h278.8e475a8
```
We know that the last one is the the most recent because of the version.

We need the same functionality for docker containers to be used with our titus integration. But, how should we calculate "version" for something as loosey-goosey as a docker tag? Internally, I've seen several ways:
- branch tag: `master-h100.6dd473f` (branch-jenkinsJob#.commitSha)
- semver tag: `v6.0.379-h403.65abf43` (version-jenkinsJob#.commitSha)
- ever increasing numbers for a tag: `124`
- updating an existing tag: like `release` updating to a new digest

Is there an industry preferred or standard version?
Should we have an opinion about versioning of docker containers?
Should we trigger on all new tags (and assume a new tag is the "next version" - like we do for docker triggered pipelines with no options specified)?
Should we make people provide a regex to match the tag, but default to an opinion? (sort of like we do with docker triggered pipelines)?
Do we need to store the time we saw an update if we can't sequentially compare versions? (i.e. like someone provides a regex and so we don't know how to sort the version)?

**Comment by emjburns** [comment]
My best direction is as follows:
- create some comparators (semver, ever-increasing number)
- allow you to choose which comparator to use for your tag
- default to using the whole tag, but allow you to specify a regex to parse your tag into a string which will be compared with the comparator you choose

I want this to be flexible and pluggable so that you can apply it to many docker image patterns without needed to edit code. However, if you want a new comparator, you'll need to add it in code.

**Comment by luispollo** [comment]
@emjburns @robfletcher Why is this in "Needs review"? Wasn't this closed by #620?

**Comment by luispollo** [comment]
Follow-up: I see it needs other things for completion, but maybe move it to "In progress" then?

**Comment by emjburns** [comment]
🤷‍♀ I always do the auto-close thing wrong. I'm doing the finishing work for this right now, i'll move it back to in progress
