### ISSUE TITLE
Keel is fast. Too fast. Also, not accurate.

### ISSUE THREAD

**Issue by emjburns** [spinnaker/keel#595]
It looks like we're considering a resource to have a "resolved" desired state long before a task finishes or clouddriver would actually consider it up.

I think this is a problem with how we're checking current state - I think we're not correctly taking into account health, active server group, etc. 

For example, this picture shows a task running, and the `keel-prestaging` cluster in the MD state of "valid" (history at this point shows events of this order (1) valid (2) delta resolved (3) actuation launched (4) diff detected). But! the new version of the cluster is definitely not healthy yet, or even fully scaled up. We are too hasty to mark as valid.
 
<img width="654" alt="Screen Shot 2019-11-08 at 11 33 14 AM" src="https://user-images.githubusercontent.com/8454927/68505359-d76f7580-021b-11ea-9767-62cd369ad900.png">

**Comment by asher** [comment]
This is primarily an issue with how `actuationInProgress` is called for multi-region resources. In this particular example, the active keel-prestaging deploy was running with the correlationId `ec2:cluster:mgmt:keel-prestaging{us-west-2}` but `ClusterHandler.actuationInProgress()` was only evaluated for the unused id `ec2:cluster:mgmt:keel-prestaging`. There's definitely a larger issue to resolve around how keel should account for cluster health but sorting out correlation ids should shift this issue from the norm to a rare corner case.
