### ISSUE TITLE
Cluster export not correctly showing varied capacity by region

### ISSUE THREAD

**Issue by emjburns** [spinnaker/keel#623]
When you export a cluster with different capacity in each region, we fail to generate the overrides section with the correct capacity for each region. Instead, we might just pick one capacity and output that?

**Comment by emjburns** [comment]
@asher is this fixed with your scaling policy PR?

**Comment by asher** [comment]
@emjburns yes, https://github.com/spinnaker/keel/pull/667/files#diff-0396cf5d5d5edd00ce4a4509bc81fe07R262-R271 adds override support for both scaling and capacity.
