### ISSUE TITLE
Separate "pause" from vetos, make instantly responsive

### ISSUE THREAD

**Issue by emjburns** [spinnaker/keel#638]
Since we're switching vetos to happen after diffing, we should separate the functionality that supports pausing and make it something a bit more first class. We should also make the unpausing and pausing reflect instantaneously.

@erikmunson got any api preferences?

**Comment by erikmunson** [comment]
In preparation for further UI work, I'd specifically like to see the pause idea get applied in a way that could 'just work' for the three main scopes of things you might want to pause:

- **Entire app**
- **Entire environment**
- **Specific resource**

I'm not really opinionated on whether each version of a pause/unpause should be its own endpoint vs. just toggles/options on a unified endpoint.

One important thing to figure out if we go that direction: what should the behavior be when you pause/unpause different scopes? If I pause a resource, then the environment it lives in, then _unpause_ the environment, should the resource I originally paused get unpaused? Intuitively I kind of think yes. In other words, should we have things that live 'within' the thing your pausing/unpausing adopt whatever state you choose, even if you had toggled their pause state individually beforehand?

**Comment by anotherchrisberry** [comment]
> If I pause a resource, then the environment it lives in, then unpause the environment, should the resource I originally paused get unpaused?
It might be nice to make this cascading behavior optional, allowing users to select all/none/specific resources to unpause.

It's hard to know until we have people actually using this stuff! But I could see a scenario where a user paused an environment after pausing, say, a security group, and they want to unpause the environment to see if their manual security group changes fixed an issue and they don't want to commit/update the YAML definition for the security group just yet.

**Comment by emjburns** [comment]
The way I can best reason about this is that every pause/resume action will affect all individual resources in its own scope.

That means if you pause a resource, then unpause the application, that resource will get unpaused. 

I think that's a fine first pass (anything else seems like an explosion of complication).
