### ISSUE TITLE
Modify export API to output delivery configs, not resources

### ISSUE THREAD

**Issue by luispollo** [spinnaker/keel#677]
Currently, the export API is outputing resource specs. Since we've decided not to support submitting individual resources to keel any longer, we need to change the export to return delivery configs.

**Comment by anotherchrisberry** [comment]
I have lots of opinions on this — let me know when you are thinking of starting so we can talk through it!

**Comment by asher** [comment]
It may remain useful to allow export of individual resources, i.e. to add to an environment in an already existing delivery config. I've also been considering building some audit functionality on top of the existing resource export, where it seems useful to be able to generate a keel resource spec with overrides from a moniker. I'd prefer to see deliveryConfig export functionality extend resource-level export without replacing it, if this approach wouldn't be overly complex or painful.

**Comment by anotherchrisberry** [comment]
Agree with @asher — there is lots of value in retaining resource-level export.

**Comment by luispollo** [comment]
Thanks for the feedback, guys. I’ll reword the issue accordingly. In fact, I’m now questioning the need/usefulness of exporting delivery configs in the first place. Would we be able to infer anything other than resources from existing infrastructure? I don’t think it would be safe to guess at environment names from monikers, for instance. If we’re adding support for onboarding apps in the UI, maybe the stuff around resources in the delivery config would come from user input?

**Comment by anotherchrisberry** [comment]
@luispollo Yeah, that is basically what I'm thinking. We'd let users pick resources and assign them to environments, then generate the YAML from that.

**Comment by luispollo** [comment]
Thanks @anotherchrisberry. Should we close this, then? @asher any thoughts?

**Comment by emjburns** [comment]
I'd like to open a new issue around export support for delivery configs (basically, for the apis that @anotherchrisberry needs for the UI). Fine to close this issue.

I agree that it's helpful to export individual resources. For some things there's no way we're going to know exactly what the user wants from export (env names like you mentioned, referencing artifacts, etc) and that's ok. We will either build other apis for that, or you'll have to do it yourself.
