### ISSUE TITLE
Flapping: let's just stop after a bit

### ISSUE THREAD

**Issue by emjburns** [spinnaker/keel#722]
With ASG deployments we have the potential to have a big negative impact if we launch 100s of instances that fail to come up, and we keep trying.

A suggestion from @ajordens is to stop after 5, and force the user to touch something to get it to try again.
We should also notify them on 5 failures or at least notify ourselves.

This will make it easier to roll out keel without being as worried about creating a ton of "bad" infra.

**Comment by jonsie** [comment]
Jumping into this project without a ton of context, but I wonder if there should be multiple ways to stop a retry. For example,

- The default behavior is that the retry will occur indefinitely, but after a configured number of failed attempts it can notify the owner to pause and take manual action.  
- If the user knows ahead of time that this is not something they want retried indefinitely, they could add some configuration to fail if there is a persistent failure.

**Comment by robzienert** [comment]
Pretty strongly disagree on this problem statement, so much so I think it's a non-issue.

If keel is finds a delta in that it needs to deploy a server group, it should be deterministically resolving the server group sequence, (e.g. `-v001`) and detect that the server group has already been created. As far as satisfying the resource DAG, the launch configuration and server group will be converged and it would be left to converging on healthy instances. It would be pathological behavior on Keel's part to deploy yet another server group if the instances in the prior created server group didn't come up.

The expectation of Keel is that it's going to continually try to converge on the desired state. If there's a delta, I would want (as a user) for Keel to continue to try, and if it can't converge on the desired state, it would detect this and then send me a notification to resolve out-of-band (be it manually satisfying some dependency, rolling back, etc). If Keel decides to give up converging on a particular resource, the delta would only continue to grow and make it harder and harder to converge on the desired state as drift expands.

**Comment by robzienert** [comment]
This issue, in my mind, raises some red flags for the MD team to consider: It sounds like from this issue, it's assumed that resource handlers are not idempotent. If that's the case, I think some brakes need to be pumped to revisit some core design choices.

**Comment by ajordens** [comment]
To slightly reframe ... my worry was just around continued creation of "bad" infra. 

If that's impossible that awesome, and this worry is unfounded and the issue close!

**Comment by asher** [comment]
@robzienert I'm not thinking of any cases where resource handlers aren't idempotent. Re:

> It would be pathological behavior on Keel's part to deploy yet another server group if the instances in the prior created server group didn't come up.

Keep in mind that the never-came-up server group isn't going to exist on future desired state calculations. When the instances fail to come up in a new server group, we intend to promise that the cluster will be left in the last good state. The new/bad server group needs to be removed, and a mechanism is required to prevent that pathological behavior. The veto mechanism that @emjburns implemented is based on a sha of the desired state - it is an actuation veto on a specific desired state of a resource, it is not a veto on the resource itself. I think we additionally need a mechanism to mark artifact versions as bad at the environment level.

**Comment by emjburns** [comment]
This worry/issue is resolved now AFAIK with artifact blacklisting + cutting way down on the number of times we will try to deploy a server group and fail. Closing.
