### ISSUE TITLE
Ensure failed multi-region cluster deploys converge back to last-good state

### ISSUE THREAD

**Issue by asher** [spinnaker/keel#772]
Given a multi-region cluster with a new artifact version that will always fail to come up in just 1 region, we can currently get into the state where one region is running the new artifact, another is on the old, and keel will simply keep attempting to deploy to the old region until the flapping veto is engaged, leaving the cluster in an inconsistent state.

To address, I propose we implement the ability to mark an `(environment_uid, artifact_uid, artifact_version)` tuple as "bad". This can occur after a configurable number of retries, but once marked, the `desired` state of the old cluster should change to the prior deployed version so that instead of remaining vetoed and inconsistent, the cluster is returned to a consistent state.

**Comment by emjburns** [comment]
This makes sense to me. 

Would we ever retry a version that is marked "bad"? I think at first no (with the assumption that it's bad code), but maybe in the future we'd want to (maybe infra is configured wrong)? For that case, we could take a hash of the server group configuration and retry if that changed?

**Comment by asher** [comment]
For an initial implementation, I'm inclined to offer a REST method to re-approve a bad artifact version for an environment but nothing that would do so automatically. What to do if a spec change results in an actuation for reasons other than the artifact version is worth further thought, along with other scenarios that might warrant automated revisiting of a version marked bad. 

Off the top of my head, we can't currently determine if the intent of spec change is to unblock a bad version. If changing the spec of a cluster undoes the prior "mark-as-bad" decision, but the change wasn't intended to unblock that version, the resulting behavior would appear incorrect and unsafe to the user, in addition to seriously delaying the successful convergence of their spec change. Requiring an additional step to retry the version at least ensures actions are in-line with intentions.

**Comment by emjburns** [comment]
That sounds good to me - manual action to retry a "bad" or unsuccessful version seems safe and predictable. You're right about not being able to determine if the intent was to fix the version.

**Comment by erikmunson** [comment]
@asher do you consider this done? Or are there other loose ends to tie?
