### ISSUE TITLE
ResourceTaskFailed and ResourceTaskSucceeded events should include a "tasks" list

### ISSUE THREAD

**Issue by erikmunson** [spinnaker/keel#829]
Per [this PR discussion](https://github.com/spinnaker/deck/pull/7939#discussion_r383512559), we should take the exact same `tasks` list that's [present on `ResourceActuationLaunched`](https://github.com/spinnaker/keel/blob/master/keel-core/src/main/kotlin/com/netflix/spinnaker/keel/events/ResourceEvent.kt#L200) and add it to `ResourceTaskFailed` and `ResourceTaskSucceeded` events.

(cc @gal-yardeni)

**Comment by gal-yardeni** [comment]
@erikmunson Thanks for adding this issue! will work on it as soon as I can!

**Comment by erikmunson** [comment]
Closed via #844
