### ISSUE TITLE
Fix unnecessary (no-op) bakes

### ISSUE THREAD

**Issue by luispollo** [spinnaker/keel#856]
From Michael:
> After an initial bake, there are lots of redundant bakes which fail after a few seconds. I believe this is not a new issue, but wanted to flag it anyway.

Discussion notes:
> The problem is we're waiting to see the image reflected in the cache, and it takes a while because we have lots of images. This is made worse when swabbie isn't running. Hurts the quality of the experience, and could overwhelm the bakery with lots of users.

**Comment by emjburns** [comment]
I've "fixed" this for now by configuring the baking to not happen a million times (limit to 2) - @robfletcher, do you need to cary this over some how to your new PR (https://github.com/spinnaker/keel/pull/886#pullrequestreview-384092893)?
