### ISSUE TITLE
User-friendly deployment and constraint notifications

### ISSUE THREAD

**Issue by luispollo** [spinnaker/keel#857]
Reported by @michaelgalloway:

> Notifications could be more clear: “Upsert server group” is not very helpful. That’s effectively any change that’s happening to a server group (including a deployment)
> 
> Rather than the operation (ex: upsert), I'd expect to see things like:
> - Deploying new artifact...
> - Completed the deployment of artifact...
> - Running canary
> etc.
> 
> Those are all messages that have immediate clarity for me and give me comfort knowing that what I'm expecting to happen is happening.

**Comment by emjburns** [comment]
Fixed for the `Upsert` tasks - we now include the version so the message is waaaaaay better. This still applies for other things I'm sure.

**Comment by marchello2000** [comment]
Not sure if this is the right place, but i think if we can make the following a link, it would make the notification much more user friendly
![image](https://user-images.githubusercontent.com/9469228/84932592-63d2f800-b089-11ea-934b-b96dcef4d782.png)

**Comment by gal-yardeni** [comment]
@marchello2000 more improvements on artifacts visualizations to come! :)
