### ISSUE TITLE
Surface stateful constraints for the UI via ArtifactSummaryInEnvironment

### ISSUE THREAD

**Issue by erikmunson** [spinnaker/keel#888]
In order to show users the current state of constraints for the artifacts they care about, we need to surface _all_ the relevant constraints for a given artifact + environment combination in the API. Mockups look roughly like this:

<img width="905" alt="Screen Shot 2020-03-17 at 6 45 05 PM" src="https://user-images.githubusercontent.com/1850998/76917043-8afa0d80-687f-11ea-9789-cc170d16223d.png">

[The `ArtifactSummaryInEnvironment` class](https://github.com/spinnaker/keel/blob/368312c2962076c06c44465fe09937888f879707/keel-core/src/main/kotlin/com/netflix/spinnaker/keel/core/api/ArtifactSummary.kt#L25-L34) already summarizes similar information — when a version was deployed to a specific environment, when it was replaced by another version, etc. It makes sense to also summarize constraints here.

Here's some example JSON that @luispollo and I sketched out a while ago, all the fields are already present in the database:
```ts
{
  name: "test",
  state: "current",
  deployedAt: "2019-12-04T18:49:58.748Z",
  replacedAt: "2019-12-04T18:49:58.748Z",
  replacedBy: "keel-0.344.0-h280.966f877",
  constraints: [
    {
      // we need some kind of 'StatefulConstraintSummary' type
      // similar to ResourceSummary.
      type: "manual-judgement",
      // can be one of: NOT_STARTED | PENDING | PASS | FAIL | OVERRIDE_PASS | OVERRIDE_FAIL
      status: "PASS",
      startedAt: "2019-12-04T18:49:58.748Z",
      judgedBy: "emunson@netflix.com",
      judgedAt: "2019-12-04T18:49:58.748Z",
      comment: "It's so cool we can declaratively deliver",
      attributes: {
        // arbitrary key/value metadata, but strongly typed by constraint type
        // so we can get type safety on the client
      }
    }
  ]
},
```

An important nuance: we don't actually write these out to the DB until they get kicked off and enter a `PENDING` status. In the API/UI, we need to surface them _before_ that so users can see a grey indicator that the constraint will eventually run. Our current proposal is to add a 'synthetic' `NOT_STARTED` status for constraints that are defined in the delivery config, but haven't run and ended up in the DB yet.

**Comment by erikmunson** [comment]
It's also likely for some constraint types like canary we'll want to also have a way to include data in the `attributes` field while in this new `NOT_STARTED` state — e.g. for canaries we'd want to still include the canary config ID and some other details about what will run in the future. Not important for a first version, and should likely become another issue when relevant.

**Comment by luispollo** [comment]
@erikmunson @asher What do we want to do about the top-level `currentEnvironmentConstraints` in the API response after we implement #888 and #889?

**Comment by erikmunson** [comment]
> @erikmunson @asher What do we want to do about the top-level `currentEnvironmentConstraints` in the API response after we implement #888 and #889?

I don’t have a strong opinion here because nothing on the UI side uses it at the moment.  I’d be perfectly happy phasing that field out if integration tests etc can get away with using the newer fields, else lets just keep it around.
