### ISSUE TITLE
Resource missing association with delivery config

### ISSUE THREAD

**Issue by luispollo** [spinnaker/keel#912]
Currently, we do not have a reference from the `resource` table to `delivery_config`. We only have a column with the application name. Having the delivery config UID would be required to allow multiple delivery configs per application and still have the children associated with the corresponding parent delivery config.

**Comment by emjburns** [comment]
We have a mapping for which environment the resource is in in the `environment_resource` table. We have a mapping for which delivery config an environment goes with in the `environment` table. This allows us to associate resources with delivery configs. I'm going to close this since this exists.
