### ISSUE TITLE
Expose pinning through the API, harden pinning

### ISSUE THREAD

**Issue by emjburns** [spinnaker/keel#979]
Pinning has been implemented in keel but not exposed through gate or hardened. This issue is tracking that work.

**Comment by luispollo** [comment]
@emjburns This can be closed after the change in `EnvironmentArtifactPin` you made in https://github.com/spinnaker/gate/pull/1154, right?

**Comment by emjburns** [comment]
I'm going to leave it open until we use pinning more, I have a feeling there are other bugs I might need to look at.

**Comment by luispollo** [comment]
@emjburns Closing this as feedback on pinning experience has been consistently good so far. Feel free to reopen.
